### ISSUE TITLE
Error in MS_Regress_Fit

### ISSUE THREAD

**Issue by chitwan24** [msperlin/MS_Regress-Matlab#2]
In `line 281` of `MS_Regress_Fit.m` , there seems some problem as the line appended below output of MS_Regress_Lik comes infinitly, I had waited for 1 hour for it to terminate but it does not terminate.
```
[param]=fminsearch(@(param)MS_Regress_Lik(dep,indep_nS,indep_S,param,k,S,advOpt,dispOut),param0,options);
```
I am getting `Sum log likelihood for MS Model -> {{number}}`  infinitly

**Comment by chitwan24** [comment]
@msperlin Please review it.

**Comment by msperlin** [comment]
Hi chitwan,

Try running the examples from the zip file. Do they run well?

The issue is likely due to the nature of your data. It means the algorithm is having a hard time finding the solution of the model. Try removing outliers from the explained data and, divide it by 100 (sometimes it works). 

Also, make sure you are modeling a stationary time series. For example, a common mistake is to model prices of stocks, and not returns. 

Best,

**Comment by chitwan24** [comment]
I tried the example from zip file named as Example_FEX.txt . It is working correctly.
So as the input is a text file , It is not clear how that file is created , I mean how was the data created, what the values in the file stand for?  It will be helpful to know this as I can input my data in the similar format as Example_FEX.txt, otherwise my problem of non terminating output : ```Sum log likelihood for MS Model -> {{number}}``` infinitly continues to remain....

**Comment by msperlin** [comment]
Chitwa, you can open the text file and check its contents. It is just a delimitated data file. Its content is a series of returns from a stock. 

It seems you're having problems importing the data. Try checking the manual of Matlab for that. 

Best,
